name: Long running

on: 
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 10s
  
  additional_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Extra job completed!"
